### ISSUE TITLE
Cannot work with Swift 3+

### ISSUE THREAD

**Issue by pimpalaputty** [natemann/PlaidClient#6]
After pod install there is 268 errors in the workspace because the AlamoFire 3.5.1 dependency is not compatible with Swift 3+. Could you update the pod?

**Comment by natemann** [comment]
@pimpalaputty, done. I have been working on a new release that removes the AlamoFire as a dependency.

**Comment by pimpalaputty** [comment]
Thanks. I figured that the version in the cocoapods  repository is not up to date, so have to install from the github repo. Everythink works great now! Good job!
