### ISSUE TITLE
PIN is being passed to connect method

### ISSUE THREAD

**Issue by pimpalaputty** [natemann/PlaidClient#7]
Hi,

I think I found a bug.

PlaidURL.connect is handling well the optional "pin" parameter, but the PlaidClient.login is not passing it to the connect function (row 94)
`let url = plaidURL.connect(clientID: clientIDToken, secret: secretToken, institution: institution, username: username, password: password)`

Could you review my suggestion?

Best,
Istvan

**Comment by natemann** [comment]
@pimpalaputty, thanks. Fixed the issue and created a new release
